on:
  push:
    branches:
      - 'main'

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
      
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1.3
      with:
        envkey_VITE_HOME: ${{ secrets.SECRET_KEY }}
        file_name: .env
        fail_on_empty: true
        directory: $GITHUB_WORKSPACE
    - run: npx nx run build
    - name: Deploy pages
      uses: crazy-max/ghaction-github-pages@v2
      with:
        build_dir: dist/action-secret
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
