on:
  push:
    branches:
      - 'main'

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1.3
      with:
        envkey_VITE_HOME: ${{ secrets.SECRET_KEY }}
        file_name: .env
        fail_on_empty: true
    - id: build-publish
      uses: bitovi/github-actions-react-to-ghp@v1.1.1
        path: dist/action-secret